project:
  type: website

website:
  title: "portfolionina"
  site-url: https://thecleahishakiye-svg.github.io/PortfolioNina/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



