project:
  type: website
  output-dir: docs

website:
  title: "portfolionina"
  site-url: https://thecleahishakiye-svg.github.io/PortfolioNina/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



